@echo off
REM clean.bat - Remove all auxiliary and temporary files generated by LaTeX compilation.

echo Cleaning auxiliary files...
del /Q main.aux main.bbl main.blg main.glg main.glo main.gls main.ist main.loa main.lof main.lol main.lot main.toc main.acn main.acr main.alg main.out main.log main.fdb_latexmk main.synctex.gz main.fls main.synctex(busy) main.bcf main.run.xml 2>nul

echo Cleaning .eps and .svg image folders...
rmdir /S /Q figures-converted 2>nul

echo Clean complete.
