@echo off
REM clean.bat - Remove all auxiliary and temporary files generated by LaTeX compilation.
REM This script deletes common LaTeX build files (.aux, .bbl, .blg, .glg, .glo, .gls, .ist, .loa, .lof, .lol, .lot, .toc, .acn, .acr, .alg, .out, .log)
REM from the main directory and also cleans up PDF, log, aux, out, and tmp files from figures, logos, and svg-inkscape folders.

del /Q main.aux main.bbl main.blg main.glg main.glo main.gls main.ist main.loa main.lof main.lol main.lot main.toc main.acn main.acr main.alg main.out main.log main.fdb_latexmk main.synctex.gz main.fls main.synctex(busy) 2>nul

echo Cleaning svg-inkscape folders (PDF, log, aux, out, and temp files)...
rmdir /S /Q figures-converted 2>nul

echo Clean complete.
